# Tour catalogue extracted from the Travique "Discover Chiang Mai" booklet.
# Each tour maps to a booklet page image in static/img so the site looks like the booklet.

TOURS = [
    {
        "id": "elephant-half",
        "img": "page04.jpg",
        "title": "Elephant Sanctuary",
        "tagline": "Meet Chiang Mai's Gentle Giants",
        "duration": "Half Day",
        "price": 1300,
        "kid_price": 700,
        "slots": ["Morning (8:00 AM pickup)", "Afternoon (12:30 PM pickup)"],
        "highlights": [
            "Feed elephants", "Mud baths with elephants", "Walk through nature",
            "Lunch included", "English speaking guide", "Hotel pick up & drop off",
        ],
    },
    {
        "id": "elephant-waterfall",
        "img": "page05.jpg",
        "title": "Elephants & Sticky Waterfall",
        "tagline": "Giants & Waterfalls",
        "duration": "Full Day",
        "price": 1700,
        "kid_price": 1100,
        "slots": ["Full Day (8:00 AM pickup)"],
        "highlights": [
            "Feed elephants", "Mud baths with elephants",
            "Walk & climb the cascading Sticky Waterfall",
            "Lunch included", "English speaking guide", "Hotel pick up & drop off",
        ],
    },
    {
        "id": "chiang-rai",
        "img": "page06.jpg",
        "title": "Chiang Rai — White Temple",
        "tagline": "White Temple, Blue Temple, Black Museum & Hot Springs",
        "duration": "Full Day",
        "price": 1500,
        "kid_price": 1200,
        "slots": ["Full Day (7:00 AM pickup)"],
        "highlights": [
            "Visit the Hot Springs on the way", "Famous White Temple",
            "Visit the Blue Temple", "Tour inside the Black Museum",
            "Lunch included", "English speaking guide", "Hotel pickup & drop off",
        ],
    },
    {
        "id": "chiang-rai-full",
        "img": "page07.jpg",
        "title": "Full Chiang Rai",
        "tagline": "Temples, Karen Village, Boat Ride & Golden Triangle",
        "duration": "Full Day",
        "price": 2000,
        "kid_price": 1550,
        "slots": ["Full Day (7:00 AM pickup)"],
        "highlights": [
            "White Temple", "Black Museum", "Blue Temple", "Karen Village",
            "Boat ride", "Hot Springs", "Golden Triangle",
            "Lunch included", "English speaking guide", "Hotel pickup & drop off",
        ],
    },
    {
        "id": "doi-suthep",
        "img": "page08.jpg",
        "title": "Doi Suthep & Hmong Village",
        "tagline": "Sacred temple & mountain viewpoint",
        "duration": "Half Day",
        "price": 1200,
        "kid_price": 850,
        "slots": ["Morning (8:00 - 8:30 AM pickup)"],
        "highlights": [
            "Visit Wat Phra That Temple", "Doi Suthep Viewpoint",
            "Experience Hmong Village", "English speaking guide",
            "Hotel pickup & drop off",
        ],
    },
    {
        "id": "doi-inthanon",
        "img": "page09.jpg",
        "title": "Doi Inthanon National Park",
        "tagline": "Visit Thailand's Highest Peak",
        "duration": "Full Day",
        "price": 1500,
        "kid_price": 1100,
        "slots": ["Full Day (8:00 AM pickup)"],
        "highlights": [
            "Explore lush mountain landscapes",
            "Trek Kew Mae Pan nature trail & 2 Waterfalls",
            "Scenic King & Queen's Pagoda viewpoints",
            "Traditional Hmong Village", "Lunch included",
            "English speaking guide", "Hotel pickup & drop off",
        ],
    },
    {
        "id": "sacred-3-temples",
        "img": "page10.jpg",
        "title": "Sacred Journey — 3 Temples",
        "tagline": "Monk blessings & cultural insights",
        "duration": "Half Day",
        "price": 1990,
        "kid_price": None,
        "slots": ["Morning", "Afternoon"],
        "highlights": [
            "Visit 3 Famous Temples", "Monk Blessing Experience",
            "Stories & Cultural Insights", "Temple Offerings Included",
            "English Guided Tour",
        ],
    },
    {
        "id": "five-temples",
        "img": "page11.jpg",
        "title": "5 Temples Blessings",
        "tagline": "Love · Health · Wealth · Career",
        "duration": "Half Day",
        "price": 3490,
        "kid_price": None,
        "slots": ["Morning", "Afternoon"],
        "highlights": [
            "Visit 5 Famous Temples in the Old Town", "Monk Blessing Experience",
            "Historical & Cultural Insights", "Temple Offerings Included",
            "English Guided Tour", "Lunch Included", "Hidden Local Stops",
            "Complimentary Spiritual Souvenir",
        ],
    },
    {
        "id": "bamboo-rafting",
        "img": "page12.jpg",
        "title": "Bamboo Rafting & Elephants",
        "tagline": "Trekking, waterfall & water rafting",
        "duration": "Full Day",
        "price": 1800,
        "kid_price": 1300,
        "slots": ["Full Day (8:00 AM pickup)"],
        "highlights": [
            "Bamboo water rafting", "Feed elephants", "Mud baths with elephants",
            "Jungle trekking with waterfall", "Lunch included",
            "English speaking guide", "Hotel pick up & drop off",
        ],
    },
    {
        "id": "full-day-nature",
        "img": "page13.jpg",
        "title": "Full Day Nature",
        "tagline": "Rafting, Sticky Waterfall & Elephants",
        "duration": "Full Day",
        "price": 2000,
        "kid_price": 1300,
        "slots": ["Full Day (8:00 AM pickup)"],
        "highlights": [
            "Bamboo water rafting", "Feed elephants", "Mud baths with elephants",
            "Sticky Waterfall view & climb", "Lunch included",
            "English speaking guide", "Hotel pick up & drop off",
        ],
    },
    {
        "id": "cooking-class",
        "img": "page14.jpg",
        "title": "Thai Cooking Class",
        "tagline": "Learn authentic recipes",
        "duration": "Half Day",
        "price": 900,
        "kid_price": None,
        "slots": ["Morning", "Afternoon"],
        "highlights": [
            "Explore local market", "Pick fresh ingredients from organic farm",
            "Cook 4 authentic Thai dishes", "Enjoy your creations",
        ],
    },
    {
        "id": "sip-thailand",
        "img": "page15.jpg",
        "title": "Sip Thailand — Wine Experience",
        "tagline": "Five wines & five curated Thai pairings",
        "duration": "~2 Hours",
        "price": 3500,
        "kid_price": None,
        "slots": ["12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM"],
        "highlights": [
            "5 selected wines", "5 signature Thai bites",
            "Guided pairing experience", "Complimentary transport",
        ],
    },
    {
        "id": "cocktail-experience",
        "img": "page16.jpg",
        "title": "Cocktail Experience",
        "tagline": "Shake · Sip · Create — hands-on mixology",
        "duration": "45 - 90 mins",
        "price": 1490,
        "kid_price": None,
        "slots": ["12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM"],
        "highlights": [
            "Welcome drink on arrival", "Learn classic cocktails",
            "Create your own signature cocktail", "10% off drinks after class",
            "Group photos & videos", "All equipment & ingredients provided",
        ],
    },
]

TOURS_BY_ID = {t["id"]: t for t in TOURS}
